/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from 'kysely';

export type Generated<T> =
    T extends ColumnType<infer S, infer I, infer U>
        ? ColumnType<S, I | undefined, U>
        : ColumnType<T, T | undefined, T>;

export interface AlbumImages {
    album_id: string;
    file_id: string;
}

export interface Albums {
    created_at: Generated<Date>;
    created_by: Generated<number | null>;
    id: string;
    name: Generated<string | null>;
}

export interface ApiKeys {
    created_at: Generated<Date>;
    id: Generated<number>;
    key: string;
    name: string;
    user_id: number;
}

export interface Files {
    id: string;
    mime_type: string;
    original_name: string;
    size: number;
    upload_date: Generated<Date>;
    uploaded_by: Generated<number | null>;
}

export interface FolderFiles {
    file_id: string;
    folder_id: string;
}

export interface Folders {
    created_at: Generated<Date>;
    created_by: number;
    id: string;
    name: string;
}

export interface Users {
    id: Generated<number>;
    password: string;
    username: string;
}

export interface DB {
    album_images: AlbumImages;
    albums: Albums;
    api_keys: ApiKeys;
    files: Files;
    folder_files: FolderFiles;
    folders: Folders;
    users: Users;
}
